name: Release Please

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the entire history is fetched for Release Please

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Release Please
        run: npm install -g release-please

      - name: Run Release Please
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release-please release-pr --token=${GITHUB_TOKEN} --repo-url=https://github.com/henzard/ha_wp_publisher.git
