name: Release Please

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for Release Please to access the commit history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Release Please requires Node.js

      - name: Install Release Please
        run: npm install -g release-please

      - name: Run Release Please
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release-please release-pr
